# 1 Numpy

In [1]:
import numpy as np

In [2]:
a=np.random.random((2,2))

In [3]:
a

array([[0.23931552, 0.75187026],
       [0.01237283, 0.59763569]])

In [4]:
a[0,0]

0.239315522000634

In [5]:
a[1,0]

0.012372825428552892

In [6]:
a.round(2)

array([[0.24, 0.75],
       [0.01, 0.6 ]])

In [7]:
a

array([[0.23931552, 0.75187026],
       [0.01237283, 0.59763569]])

In [9]:
a[0]

array([0.23931552, 0.75187026])

In [11]:
a[:,0]

array([0.23931552, 0.01237283])

In [12]:
b=np.random.random((4,3,2))

In [13]:
#three dimensional tensor
b

array([[[0.10813192, 0.86231848],
        [0.54852418, 0.18924932],
        [0.45150818, 0.28630058]],

       [[0.25483113, 0.39519883],
        [0.73571869, 0.04890793],
        [0.03546335, 0.22034117]],

       [[0.03277576, 0.81557573],
        [0.01679562, 0.04379091],
        [0.15709571, 0.5952473 ]],

       [[0.31365547, 0.96122203],
        [0.41702875, 0.77736893],
        [0.48300629, 0.8531904 ]]])

In [14]:
#4 dimensional tensor
c=np.random.random((5,4,3,2))

In [15]:
b[3]

array([[0.31365547, 0.96122203],
       [0.41702875, 0.77736893],
       [0.48300629, 0.8531904 ]])

In [18]:
b[3,1]

array([0.41702875, 0.77736893])

In [19]:
b[:,1]

array([[0.54852418, 0.18924932],
       [0.73571869, 0.04890793],
       [0.01679562, 0.04379091],
       [0.41702875, 0.77736893]])

In [20]:
b[:,:,0]

array([[0.10813192, 0.54852418, 0.45150818],
       [0.25483113, 0.73571869, 0.03546335],
       [0.03277576, 0.01679562, 0.15709571],
       [0.31365547, 0.41702875, 0.48300629]])

# 2. Lambda functions

In [21]:
def square_function (x):
    return x*x

In [23]:
square_function(2)

4

In [25]:
ssquare=lambda x: x*x

In [26]:
ssquare(2)

4

In [27]:
summator=lambda x,y: x+y

In [28]:
summator(2,3)

5

In [30]:
div=lambda x,y: x/y if y!=0 else 0

In [31]:
div(2,3)

0.6666666666666666

In [32]:
div(2,0)

0

## 2.1 Create function that returns a function

In [33]:
def generate_range (lower):
    return lambda upper: range(lower,upper)

In [35]:
range(10)

range(0, 10)

In [36]:
custom_range=generate_range(5)

In [37]:
custom_range(10)

range(5, 10)

## 2.2 Lambda + list comprehensions

In [38]:
ssquare=lambda x: x*x

In [39]:
[ssquare(i) for i in range(20)]

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361]

In [40]:
topics=['Python','MySQL','Pandas','Web Scraping','Data viz','Statistics','Machine Learning']

In [41]:
[i.lower().replace(' ','_') for i in topics]

['python',
 'mysql',
 'pandas',
 'web_scraping',
 'data_viz',
 'statistics',
 'machine_learning']

In [42]:
[(lambda x: x.lower().replace(' ','_'))(i) for i in topics]

['python',
 'mysql',
 'pandas',
 'web_scraping',
 'data_viz',
 'statistics',
 'machine_learning']

In [45]:
list(map(lambda x: x.lower().replace(' ','_'), topics))

['python',
 'mysql',
 'pandas',
 'web_scraping',
 'data_viz',
 'statistics',
 'machine_learning']

## 2.3 Another example

In [49]:
dct={i:len(i) for i in topics}

In [50]:
import operator
sorted(dct.items(), key=operator.itemgetter(1), reverse=True)

[('Machine Learning', 16),
 ('Web Scraping', 12),
 ('Statistics', 10),
 ('Data viz', 8),
 ('Python', 6),
 ('Pandas', 6),
 ('MySQL', 5)]

In [51]:
dict(sorted(dct.items(), reverse=True, key=lambda x: x[1]))

{'Machine Learning': 16,
 'Web Scraping': 12,
 'Statistics': 10,
 'Data viz': 8,
 'Python': 6,
 'Pandas': 6,
 'MySQL': 5}

## 2.4 Pros and cons

Disadvantages:
1. Not every function can be written as lambda function
2. Overcomplication in some cases

Advantages:
1. Concise
2. Short
3. Return automatically
4. Can be passed without variable

In [52]:
(lambda : 2+3)()

5

# 3 Map, Filter, Reduce

## 3.1 Map

In [54]:
def func (x):
    return x%2==0

In [55]:
l=[10,11,13,17,18]

In [57]:
func(l)

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [58]:
[func(i) for i in l]

[True, False, False, False, True]

In [59]:
list(map(func,l))

[True, False, False, False, True]

In [60]:
import pandas as pd
import numpy as np

In [61]:
df=pd.DataFrame ([[1,2,3],[2,3,np.nan]])

In [62]:
df

0  1    2
0  1  2  3.0
1  2  3  NaN

In [63]:
def ff (x):
    return float(x)

In [64]:
df[0].map(ff)

0    1.0
1    2.0
Name: 0, dtype: float64

**IMPORTANT!**
'map()' only works with pd.Series

In [66]:
df[1].map(lambda x: x**2)

0    4
1    9
Name: 1, dtype: int64

In [67]:
dct ={1:'apple',2:'plum'}

In [68]:
dct

{1: 'apple', 2: 'plum'}

In [69]:
df[0].map(dct)

0    apple
1     plum
Name: 0, dtype: object

## 3.2 Filter

In [70]:
list(map(func, l))

[True, False, False, False, True]

In [71]:
l

[10, 11, 13, 17, 18]

In [72]:
list(filter(func,l))

[10, 18]

In [74]:
df.index=['Mouse','cat']

In [75]:
df

0  1    2
Mouse  1  2  3.0
cat    2  3  NaN

In [76]:
df.filter(like='ouse', axis=0)

0  1    2
Mouse  1  2  3.0

In [77]:
df.loc[df.index.str.contains('ouse')]

0  1    2
Mouse  1  2  3.0

In [78]:
df.filter(items=[0,2], axis=1)

0    2
Mouse  1  3.0
cat    2  NaN

In [79]:
df.filter(items=[0,2])

0    2
Mouse  1  3.0
cat    2  NaN

## 3.3 Reduce

In [80]:
def func (a,b): return a+b

In [81]:
from functools import reduce

In [82]:
l

[10, 11, 13, 17, 18]

In [83]:
reduce(func, l)

69

In [84]:
sum(l)

69

In [85]:
#Select the biggest number out of 2
def func (a,b):
    return a if a>b else b

In [86]:
reduce(func,l)

18

In [87]:
l=[10,21,12,14,15]

In [88]:
reduce(func,l)

21

In [89]:
# Really dumb function just for the sake of another example

def func(a,b):
    if (b%2==0) or ((a+b)>35):
        return a
    else:
        return b

In [90]:
func(10,21)

21

In [91]:
func(21,13)

13

In [93]:
l=[10,21,13,17,18]

In [94]:
reduce(func,l)

17

# 4. MAAM - Map, Apply, ApplyMap

In [95]:
df=pd.read_csv('https://ironhack.school/asset-v1:IRONHACK+DAFT+201910_PAR+type@asset+block@IMDB-Movie-Data.csv')

In [96]:
df.head()

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0  
3     7.2   60545              270.32       59.0  
4     6.2  393727              325.02       40.0

In [97]:
df.shape

(1000, 12)

In [98]:
df.Rating.max()

9.0

In [99]:
df.Rating.min()

1.9

In [100]:
df.Rating/2

0      4.05
1      3.50
2      3.65
3      3.60
4      3.10
       ... 
995    3.10
996    2.75
997    3.10
998    2.80
999    2.65
Name: Rating, Length: 1000, dtype: float64

In [101]:
df.Rating.map(lambda x: x/2)

0      4.05
1      3.50
2      3.65
3      3.60
4      3.10
       ... 
995    3.10
996    2.75
997    3.10
998    2.80
999    2.65
Name: Rating, Length: 1000, dtype: float64

In [102]:
def column_range(x):
    """x is a pandas series"""
    return x.max()-x.min()

In [103]:
df.Rating.map(column_range)

AttributeError: 'float' object has no attribute 'max'

In [104]:
df[['Rating']].apply(column_range)

Rating    7.1
dtype: float64

In [105]:
df[['Rating','Runtime (Minutes)']].apply(column_range)

Rating                 7.1
Runtime (Minutes)    125.0
dtype: float64

In [106]:
def column_range(x):
    """x is a pandas series"""
    return x.max()-x.min() if x.dtype in (int,float) else len(x)

In [107]:
df.apply(column_range)

Rank                      999.00
Title                    1000.00
Genre                    1000.00
Description              1000.00
Director                 1000.00
Actors                   1000.00
Year                       10.00
Runtime (Minutes)         125.00
Rating                      7.10
Votes                 1791855.00
Revenue (Millions)        936.63
Metascore                  89.00
dtype: float64

* Map applies the function provided to every values of Series
* Apply apllies the function provided to every value of Series or to every Serie in DataFrame

In [108]:
df.Rating.apply(lambda x: x/2)

0      4.05
1      3.50
2      3.65
3      3.60
4      3.10
       ... 
995    3.10
996    2.75
997    3.10
998    2.80
999    2.65
Name: Rating, Length: 1000, dtype: float64

In [109]:
df.Rating.map(lambda x: x/2)

0      4.05
1      3.50
2      3.65
3      3.60
4      3.10
       ... 
995    3.10
996    2.75
997    3.10
998    2.80
999    2.65
Name: Rating, Length: 1000, dtype: float64

In [110]:
df.map()

AttributeError: 'DataFrame' object has no attribute 'map'

In [111]:
def missing_col (x):
    return x.isna().sum()

In [112]:
df.apply(missing_col)

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [113]:
df.isna().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

## 4.1 All above + lambda

In [122]:
df[df['Genre'].str.lower().str.contains('action')].head()

Rank                    Title                       Genre  \
0      1  Guardians of the Galaxy     Action,Adventure,Sci-Fi   
4      5            Suicide Squad    Action,Adventure,Fantasy   
5      6           The Great Wall    Action,Adventure,Fantasy   
8      9       The Lost City of Z  Action,Adventure,Biography   
12    13                Rogue One     Action,Adventure,Sci-Fi   

                                          Description        Director  \
0   A group of intergalactic criminals are forced ...      James Gunn   
4   A secret government agency recruits some of th...      David Ayer   
5   European mercenaries searching for black powde...     Yimou Zhang   
8   A true-life drama, centering on British explor...      James Gray   
12  The Rebel Alliance makes a risky move to steal...  Gareth Edwards   

                                               Actors  Year  \
0   Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
4   Will Smith, Jared Leto, Margot Robbie, Viola D...  2016   
5       Matt Damon, Tian Jing, Willem Dafoe, Andy Lau  2016   
8   Charlie Hunnam, Robert Pattinson, Sienna Mille...  2016   
12  Felicity Jones, Diego Luna, Alan Tudyk, Donnie...  2016   

    Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                 121     8.1  757074              333.13       76.0  
4                 123     6.2  393727              325.02       40.0  
5                 103     6.1   56036               45.13       42.0  
8                 141     7.1    7188                8.01       78.0  
12                133     7.9  323118              532.17       65.0

In [123]:
# I don't want to see action fantasy movies in my selection.

df[df['Genre'].str.lower().str.contains('action')&(~df['Genre'].str.lower().str.contains('fantasy'))]

Rank                     Title                       Genre  \
0       1   Guardians of the Galaxy     Action,Adventure,Sci-Fi   
8       9        The Lost City of Z  Action,Adventure,Biography   
12     13                 Rogue One     Action,Adventure,Sci-Fi   
14     15                  Colossal         Action,Comedy,Drama   
17     18              Jason Bourne             Action,Thriller   
..    ...                       ...                         ...   
954   955                Death Race      Action,Sci-Fi,Thriller   
958   959            3 Days to Kill       Action,Drama,Thriller   
968   969                   Wrecker      Action,Horror,Thriller   
969   970           The Lone Ranger    Action,Adventure,Western   
993   994  Resident Evil: Afterlife     Action,Adventure,Horror   

                                           Description            Director  \
0    A group of intergalactic criminals are forced ...          James Gunn   
8    A true-life drama, centering on British explor...          James Gray   
12   The Rebel Alliance makes a risky move to steal...      Gareth Edwards   
14   Gloria is an out-of-work party girl forced to ...     Nacho Vigalondo   
17   The CIA's most dangerous former operative is d...     Paul Greengrass   
..                                                 ...                 ...   
954  Ex-con Jensen Ames is forced by the warden of ...  Paul W.S. Anderson   
958  A dying CIA agent trying to reconnect with his...                 McG   
968  Best friends Emily and Lesley go on a road tri...      Micheal Bafaro   
969  Native American warrior Tonto recounts the unt...      Gore Verbinski   
993  While still out to destroy the evil Umbrella C...  Paul W.S. Anderson   

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
8    Charlie Hunnam, Robert Pattinson, Sienna Mille...  2016   
12   Felicity Jones, Diego Luna, Alan Tudyk, Donnie...  2016   
14   Anne Hathaway, Jason Sudeikis, Austin Stowell,...  2016   
17   Matt Damon, Tommy Lee Jones, Alicia Vikander,V...  2016   
..                                                 ...   ...   
954  Jason Statham, Joan Allen, Tyrese Gibson, Ian ...  2008   
958  Kevin Costner, Hailee Steinfeld, Connie Nielse...  2014   
968  Anna Hutchison, Andrea Whitburn, Jennifer Koen...  2015   
969  Johnny Depp, Armie Hammer, William Fichtner,To...  2013   
993  Milla Jovovich, Ali Larter, Wentworth Miller,K...  2010   

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                  121     8.1  757074              333.13       76.0  
8                  141     7.1    7188                8.01       78.0  
12                 133     7.9  323118              532.17       65.0  
14                 109     6.4    8612                2.87       70.0  
17                 123     6.7  150823              162.16       58.0  
..                 ...     ...     ...                 ...        ...  
954                105     6.4  173731               36.06       43.0  
958                117     6.2   73567               30.69       40.0  
968                 83     3.5    1210                 NaN       37.0  
969                150     6.5  190855               89.29        NaN  
993                 97     5.9  140900               60.13       37.0  

[263 rows x 12 columns]

I want to have a very specific selection of movies. I am a bit spoiled movie critique and I want to see the following:
1. It should be an Action movie
2. The max number of genres that movie represent is 2
3. I don't like Action Fantasy movies. So I will only accept Action with Thriller or Adventure.

['Action',
'Action, Adventure',
'Action, Thriller']


In [129]:
df[df.Genre.str.split(',').map(lambda x: len(x)<3)]; #Number of genres

df[df['Genre'].str.lower().str.contains('action')]; #Contains action

df[df['Genre'].str.lower().str.contains('action')& #option 1 for #3
   ((df['Genre'].str.lower().str.contains('thriller'))|
    (df['Genre'].str.lower().str.contains('adventure')))]

#option 2 for #3
df[df.Genre.str.lower().str.split(',').map(lambda x: (set(x)-set(['action','thriller','adventure']))==set())]

Rank                                          Title  \
17     18                                   Jason Bourne   
123   124                           Boyka: Undisputed IV   
124   125                          The Dark Knight Rises   
164   165                                  Casino Royale   
169   170                                        Spectre   
233   234             Mission: Impossible - Rogue Nation   
270   271                                        Skyfall   
282   283                                    Death Proof   
284   285                                       Hercules   
289   290                                           Iris   
344   345                                   Spider-Man 3   
368   369                         The Amazing Spider-Man   
379   380                              The Expendables 3   
410   411                                          Taken   
433   434           Mission: Impossible - Ghost Protocol   
444   445                                   The Thinning   
453   454                             Olympus Has Fallen   
560   561                                The Expendables   
580   581                           Kickboxer: Vengeance   
624   625                                        Taken 3   
698   699                          Live Free or Die Hard   
729   730                                      The Guest   
746   747                             Only for One Night   
770   771                              Quantum of Solace   
777   778                                     Final Girl   
844   845                                    Unstoppable   
848   849                                    Mean Dreams   
869   870                        Mission: Impossible III   
872   873                                       Red Dawn   
911   912  I Am the Pretty Thing That Lives in the House   
916   917                              The Expendables 2   
923   924                                      No Escape   
933   934                                         Detour   
942   943                                     Transpecos   
949   950                                          Kicks   

                         Genre  \
17             Action,Thriller   
123                     Action   
124            Action,Thriller   
164  Action,Adventure,Thriller   
169  Action,Adventure,Thriller   
233  Action,Adventure,Thriller   
270  Action,Adventure,Thriller   
282                   Thriller   
284           Action,Adventure   
289                   Thriller   
344           Action,Adventure   
368           Action,Adventure   
379  Action,Adventure,Thriller   
410            Action,Thriller   
433  Action,Adventure,Thriller   
444                   Thriller   
453            Action,Thriller   
560  Action,Adventure,Thriller   
580                     Action   
624            Action,Thriller   
698  Action,Adventure,Thriller   
729                   Thriller   
746                   Thriller   
770  Action,Adventure,Thriller   
777            Action,Thriller   
844            Action,Thriller   
848                   Thriller   
869  Action,Adventure,Thriller   
872            Action,Thriller   
911                   Thriller   
916  Action,Adventure,Thriller   
923            Action,Thriller   
933                   Thriller   
942                   Thriller   
949                  Adventure   

                                           Description               Director  \
17   The CIA's most dangerous former operative is d...        Paul Greengrass   
123  In the fourth installment of the fighting fran...        Todor Chapkanov   
124  Eight years after the Joker's reign of anarchy...      Christopher Nolan   
164  Armed with a licence to kill, Secret Agent Jam...        Martin Campbell   
169  A cryptic message from Bond's past sends him o...             Sam Mendes   
233  Ethan and team take on their most impossible m...  Christopher McQuarrie   
270  Bond's loyalty to M is tested when her past co.

In [134]:
df[df.Genre.str.lower().str.split(',').map(lambda x: (len(x)<3) 
                                           & ('action' in x) 
                                           & ((set(x)-set(['action','thriller','adventure']))==set()))]

Rank                   Title             Genre  \
17     18            Jason Bourne   Action,Thriller   
123   124    Boyka: Undisputed IV            Action   
124   125   The Dark Knight Rises   Action,Thriller   
284   285                Hercules  Action,Adventure   
344   345            Spider-Man 3  Action,Adventure   
368   369  The Amazing Spider-Man  Action,Adventure   
410   411                   Taken   Action,Thriller   
453   454      Olympus Has Fallen   Action,Thriller   
580   581    Kickboxer: Vengeance            Action   
624   625                 Taken 3   Action,Thriller   
777   778              Final Girl   Action,Thriller   
844   845             Unstoppable   Action,Thriller   
872   873                Red Dawn   Action,Thriller   
923   924               No Escape   Action,Thriller   

                                           Description           Director  \
17   The CIA's most dangerous former operative is d...    Paul Greengrass   
123  In the fourth installment of the fighting fran...    Todor Chapkanov   
124  Eight years after the Joker's reign of anarchy...  Christopher Nolan   
284  Having endured his legendary twelve labors, He...       Brett Ratner   
344  A strange black entity from another world bond...          Sam Raimi   
368  After Peter Parker is bitten by a genetically ...          Marc Webb   
410  A retired CIA agent travels across Europe and ...       Pierre Morel   
453  Disgraced Secret Service agent (and former pre...      Antoine Fuqua   
580         A kick boxer is out to avenge his brother.     John Stockwell   
624  Ex-government operative Bryan Mills is accused...    Olivier Megaton   
777  A man teaches a young woman how to become a co...      Tyler Shields   
844  With an unmanned, half-mile-long freight train...         Tony Scott   
872  A group of teenagers look to save their town f...        Dan Bradley   
923  In their new overseas home, an American family...  John Erick Dowdle   

                                                Actors  Year  \
17   Matt Damon, Tommy Lee Jones, Alicia Vikander,V...  2016   
123  Scott Adkins, Teodora Duhovnikova, Alon Aboutb...  2016   
124  Christian Bale, Tom Hardy, Anne Hathaway,Gary ...  2012   
284  Dwayne Johnson, John Hurt, Ian McShane, Joseph...  2014   
344  Tobey Maguire, Kirsten Dunst, Topher Grace, Th...  2007   
368  Andrew Garfield, Emma Stone, Rhys Ifans, Irrfa...  2012   
410  Liam Neeson, Maggie Grace, Famke Janssen, Lela...  2008   
453  Gerard Butler, Aaron Eckhart, Morgan Freeman,A...  2013   
580  Dave Bautista, Alain Moussi, Gina Carano, Jean...  2016   
624  Liam Neeson, Forest Whitaker, Maggie Grace,Fam...  2014   
777  Abigail Breslin, Wes Bentley, Logan Huffman,Al...  2015   
844  Denzel Washington, Chris Pine, Rosario Dawson,...  2010   
872  Chris Hemsworth, Isabel Lucas, Josh Hutcherson...  2012   
923  Lake Bell, Pierce Brosnan, Owen Wilson,Chatcha...  2015   

     Runtime (Minutes)  Rating    Votes  Revenue (Millions)  Metascore  
17                 123     6.7   150823              162.16       58.0  
123                 86     7.4    10428                 NaN        NaN  
124                164     8.5  1222645              448.13       78.0  
284                 98     6.0   122838               72.66       47.0  
344                139     6.2   406219              336.53       59.0  
368                136     7.0   474320              262.03       66.0  
410                 93     7.8   502961              145.00       50.0  
453                119     6.5   214994               98.90       41.0  
580                 90     4.9     6809              131.56       37.0  
624                109     6.0   144715               89.25       26.0  
777                 90     4.7     9026                 NaN       56.0  
844                 98     6.8   157499               81.56       69.0  
872                 93     5.4    64584               44.80       31.0  
923                103     6.8    57921 

## 4.2 Applymap

1. Map works with Series only
2. Apply works with both Series and DataFrame
3. Applympa works only with DataFrames

1. Map works with values in Series
2. Apply works with values in Series and Series in DataFrame
3. Applympa works with values in DataFrame

Calculate the average number of words in description and name.

In every cell of 2 columns I need:
1. Get words
2. Count them
    

In [135]:
df_d=df[['Title','Description']]

In [136]:
df_d.Description.str.split().map(len).mean()

27.921

In [137]:
df_d.Title.str.split().map(len).mean()

2.605

In [141]:
df_d.applymap(lambda x: len(x.split())).mean()

Title           2.605
Description    27.921
dtype: float64